services:
  api:
    image: ghcr.io/danny-avila/librechat-dev-api:latest
    container_name: librechat-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librechat-api.rule=Host(`chat.simplis.ai`)"
      - "traefik.http.routers.librechat-api.tls=true"
      - "traefik.http.services.librechat-api.loadbalancer.server.port=3080"
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - DOMAIN_CLIENT=https://chat.simplis.ai
      - DOMAIN_SERVER=https://chat.simplis.ai
      # ... outras variáveis

  meilisearch:
    container_name: librechat-meilisearch
    image: getmeili/meilisearch:v1.11.4
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.meilisearch.rule=Host(`meilisearch.simplis.ai`)"
      - "traefik.http.routers.meilisearch.tls=true"
      - "traefik.http.services.meilisearch.loadbalancer.server.port=7700"
    environment:
      - MEILI_HOST=http://0.0.0.0:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

  vector-db:
    image: ankane/pgvector:latest
    container_name: librechat-vector-db
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vectordb.rule=Host(`vectordb.simplis.ai`)"
      - "traefik.http.routers.vectordb.tls=true"
      - "traefik.http.services.vectordb.loadbalancer.server.port=5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  rag-api:
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    container_name: librechat-rag-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag-api.rule=Host(`rag.simplis.ai`)"
      - "traefik.http.routers.rag-api.tls=true"
      - "traefik.http.services.rag-api.loadbalancer.server.port=8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DB_HOST=vector-db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - vector-db
