services:
  api:
    container_name: SimplisAI
    image: ghcr.io/danny-avila/librechat-dev:latest
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - PORT=${PORT:-3080}
      - MONGO_URI=${MONGO_URI}
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
      - DOMAIN_CLIENT=${DOMAIN_CLIENT}
      - DOMAIN_SERVER=${DOMAIN_SERVER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CREDS_KEY=${CREDS_KEY}
      - CREDS_IV=${CREDS_IV}
      - ALLOW_REGISTRATION=false
      - ALLOW_EMAIL_LOGIN=true
      - ALLOW_SOCIAL_LOGIN=false
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - APP_TITLE=Simplis.ai
    depends_on:
      - rag_api
    volumes:
      - ./librechat.yaml:/app/librechat.yaml
      - ./branding/assets:/app/client/public/assets
      - librechat_images:/app/client/public/images
      - librechat_uploads:/app/uploads
      - librechat_logs:/app/api/logs
    networks:
      - simplis-network

  meilisearch:
    container_name: simplis-meilisearch
    image: getmeili/meilisearch:v1.12
    restart: always
    environment:
      - MEILI_HOST=http://0.0.0.0:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}
    volumes:
      - meili_data:/meili_data
    networks:
      - simplis-network

  vectordb:
    container_name: simplis-vectordb
    image: ankane/pgvector:latest
    restart: always
    environment:
      - POSTGRES_DB=simplisai
      - POSTGRES_USER=simplis
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - simplis-network

  rag_api:
    container_name: simplis-rag-api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    restart: always
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
      - HOST=0.0.0.0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
    depends_on:
      - vectordb
    networks:
      - simplis-network

volumes:
  librechat_images:
  librechat_uploads:
  librechat_logs:
  meili_data:
  pgdata:

networks:
  default:
    name: simplis-network
  simplis-network:
    name: simplis-network
